name: Update Sponsors on New Sponsorship

on:
  repository_dispatch:
    types: [sponsorship] # Triggered by the webhook
  workflow_dispatch: # Allows manual trigger

jobs:
  update-sponsors:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Webhook Secret
        env:
          SPONSOR_WEBHOOK_SECRET: ${{ secrets.SPONSOR_WEBHOOK_SECRET }}
        run: |
          if [ -z "$SPONSOR_WEBHOOK_SECRET" ]; then
            echo "Error: Webhook secret is missing!"
            exit 1
          fi
          echo "Webhook secret is set. Continuing execution..."

      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4 (latest as of March 2025)

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '16' # Stick with 16 if required, but consider upgrading if possible

      - name: Install dependencies
        run: npm install

      - name: Run SponsorKit
        run: npx sponsorkit
        env: # Ensure SponsorKit has access to these variables
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: ${{ secrets.SPONSORKIT_GITHUB_LOGIN }}

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          # Check for changes before committing
          if ! git diff --staged --quiet; then
            git commit -m "Update sponsors [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For pushing to the repo
