name: Update Sponsors on New Sponsorship

on:
  repository_dispatch:
    types: [sponsorship] # Triggered by the webhook
  workflow_dispatch: # Allows manual trigger

jobs:
  update-sponsors:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Webhook Secret
        run: |
          if [ -z "${{ secrets.SPONSOR_WEBHOOK_SECRET }}" ]; then
            echo "Error: Webhook secret is missing!"
            exit 1
          fi
          echo "Webhook secret is set. Continuing execution..."

      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Checkout custom SponsorKit
        uses: actions/checkout@v3
        with:
          repository: hm21/sponsorkit
          path: sponsorkit

      - name: Install dependencies
        run: |
          cd sponsorkit
          npm install
          npm run build

      - name: Generate Sponsors Image
        run: |
          cd sponsorkit
          node bin/sponsorkit.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sponsors.svg
          git commit -m "Update sponsors list" || echo "No changes to commit"
          git push
